# Generated by Django 4.2.5 on 2023-11-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cakevarient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakeapp.cakevarients'),
        ),
    ]
